# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0002_auto_20160311_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hikes',
            new_name='Hike',
        ),
    ]
